package dutyrostering.dutyrostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DayOffRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private dutyrostering.dutyrostering.Timeslot offShift;
	private dutyrostering.dutyrostering.Employee employee;

	public DayOffRequest() {
	}

	public dutyrostering.dutyrostering.Timeslot getOffShift() {
		return this.offShift;
	}

	public void setOffShift(dutyrostering.dutyrostering.Timeslot offShift) {
		this.offShift = offShift;
	}

	public dutyrostering.dutyrostering.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(dutyrostering.dutyrostering.Employee employee) {
		this.employee = employee;
	}

	public DayOffRequest(dutyrostering.dutyrostering.Timeslot offShift,
			dutyrostering.dutyrostering.Employee employee) {
		this.offShift = offShift;
		this.employee = employee;
	}

}