package dutyrostering.dutyrostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution(autoDiscoverMemberType = org.optaplanner.core.api.domain.autodiscover.AutoDiscoverMemberType.FIELD)
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class DutyRoster implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<dutyrostering.dutyrostering.DayOffRequest> dayOffRequestList;
	private java.util.List<dutyrostering.dutyrostering.ShiftAssignment> shiftAssignmentList;
	private java.util.List<dutyrostering.dutyrostering.Shift> shiftList;
	private java.util.List<dutyrostering.dutyrostering.Duty> dutyList;
	private java.util.List<dutyrostering.dutyrostering.Timeslot> timeslotList;
	@org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "employeeRange")
	private java.util.List<dutyrostering.dutyrostering.Employee> employeeList;

	@javax.annotation.Generated(value = {"org.optaplanner.workbench.screens.domaineditor.client.widgets.planner.PlannerDataObjectEditor"})
	@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(value = org.optaplanner.persistence.jaxb.api.score.buildin.hardsoft.HardSoftScoreJaxbXmlAdapter.class)
	@org.kie.api.definition.type.Label(value = "Generated Planner score field")
	@org.optaplanner.core.api.domain.solution.PlanningScore
	private org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score;

	public DutyRoster() {
	}

	public java.util.List<dutyrostering.dutyrostering.DayOffRequest> getDayOffRequestList() {
		return this.dayOffRequestList;
	}

	public void setDayOffRequestList(
			java.util.List<dutyrostering.dutyrostering.DayOffRequest> dayOffRequestList) {
		this.dayOffRequestList = dayOffRequestList;
	}

	public java.util.List<dutyrostering.dutyrostering.ShiftAssignment> getShiftAssignmentList() {
		return this.shiftAssignmentList;
	}

	public void setShiftAssignmentList(
			java.util.List<dutyrostering.dutyrostering.ShiftAssignment> shiftAssignmentList) {
		this.shiftAssignmentList = shiftAssignmentList;
	}

	public java.util.List<dutyrostering.dutyrostering.Shift> getShiftList() {
		return this.shiftList;
	}

	public void setShiftList(
			java.util.List<dutyrostering.dutyrostering.Shift> shiftList) {
		this.shiftList = shiftList;
	}

	public java.util.List<dutyrostering.dutyrostering.Duty> getDutyList() {
		return this.dutyList;
	}

	public void setDutyList(
			java.util.List<dutyrostering.dutyrostering.Duty> dutyList) {
		this.dutyList = dutyList;
	}

	public java.util.List<dutyrostering.dutyrostering.Timeslot> getTimeslotList() {
		return this.timeslotList;
	}

	public void setTimeslotList(
			java.util.List<dutyrostering.dutyrostering.Timeslot> timeslotList) {
		this.timeslotList = timeslotList;
	}

	public java.util.List<dutyrostering.dutyrostering.Employee> getEmployeeList() {
		return this.employeeList;
	}

	public void setEmployeeList(
			java.util.List<dutyrostering.dutyrostering.Employee> employeeList) {
		this.employeeList = employeeList;
	}

	public org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore getScore() {
		return this.score;
	}

	public void setScore(
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score) {
		this.score = score;
	}

	public DutyRoster(
			java.util.List<dutyrostering.dutyrostering.DayOffRequest> dayOffRequestList,
			java.util.List<dutyrostering.dutyrostering.ShiftAssignment> shiftAssignmentList,
			java.util.List<dutyrostering.dutyrostering.Shift> shiftList,
			java.util.List<dutyrostering.dutyrostering.Duty> dutyList,
			java.util.List<dutyrostering.dutyrostering.Timeslot> timeslotList,
			java.util.List<dutyrostering.dutyrostering.Employee> employeeList,
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score) {
		this.dayOffRequestList = dayOffRequestList;
		this.shiftAssignmentList = shiftAssignmentList;
		this.shiftList = shiftList;
		this.dutyList = dutyList;
		this.timeslotList = timeslotList;
		this.employeeList = employeeList;
		this.score = score;
	}

}