package dutyrostering.dutyrostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Duty implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public Duty() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Duty(java.lang.String name) {
		this.name = name;
	}

}