package dutyrostering.dutyrostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private dutyrostering.dutyrostering.Duty duty;

	public Employee() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public dutyrostering.dutyrostering.Duty getDuty() {
		return this.duty;
	}

	public void setDuty(dutyrostering.dutyrostering.Duty duty) {
		this.duty = duty;
	}

	public Employee(java.lang.String name, dutyrostering.dutyrostering.Duty duty) {
		this.name = name;
		this.duty = duty;
	}

}