package dutyrostering.dutyrostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shift implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private dutyrostering.dutyrostering.Duty requiredDuty;
	private dutyrostering.dutyrostering.Timeslot timeslot;

	public Shift() {
	}

	public dutyrostering.dutyrostering.Duty getRequiredDuty() {
		return this.requiredDuty;
	}

	public void setRequiredDuty(dutyrostering.dutyrostering.Duty requiredDuty) {
		this.requiredDuty = requiredDuty;
	}

	public dutyrostering.dutyrostering.Timeslot getTimeslot() {
		return this.timeslot;
	}

	public void setTimeslot(dutyrostering.dutyrostering.Timeslot timeslot) {
		this.timeslot = timeslot;
	}

	public Shift(dutyrostering.dutyrostering.Duty requiredDuty,
			dutyrostering.dutyrostering.Timeslot timeslot) {
		this.requiredDuty = requiredDuty;
		this.timeslot = timeslot;
	}

}