package dutyrostering.dutyrostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class ShiftAssignment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"employeeRange"})
	private dutyrostering.dutyrostering.Employee employee;
	private dutyrostering.dutyrostering.Shift shift;

	public ShiftAssignment() {
	}

	public dutyrostering.dutyrostering.Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(dutyrostering.dutyrostering.Employee employee) {
		this.employee = employee;
	}

	public dutyrostering.dutyrostering.Shift getShift() {
		return this.shift;
	}

	public void setShift(dutyrostering.dutyrostering.Shift shift) {
		this.shift = shift;
	}

	public ShiftAssignment(dutyrostering.dutyrostering.Employee employee,
			dutyrostering.dutyrostering.Shift shift) {
		this.employee = employee;
		this.shift = shift;
	}

}